
GET http://localhost:8080/mascotas/all

###

POST http://localhost:8080/mascotas/add
Content-Type: application/x-www-form-urlencoded

nombre=Firulais
&raza=Perro
&propietario=Juan

###

PUT http://localhost:8080/mascotas/edit
Content-Type: application/x-www-form-urlencoded

id=4
&nombre=Firulais2
&raza=Perro
&propietario=Juan
###

GET http://localhost:8080/mascotas/ver/4

###

DELETE http://localhost:8080/mascotas/del
Content-Type: application/x-www-form-urlencoded

id=4

###

GET http://localhost:8080/mascotas/get/report
